### ISSUE TITLE
Nostr Plugin: zap stopped working (Amethyst - "Could not fetch invoice from...")

### ISSUE THREAD

**Issue by Perlover** [Kukks/BTCPayServerPlugins#13]
In the beginning, everything worked. But I don't know what happened. But now, when the Lightning Address from BTCPay is registered in my profile and when I send zap to myself from the application or from the snort.social website, I see an error ("Could not fetch invoice from https://.../BTC/UILNURL/pay/i/INVOICE_ID"). Here, for example, is an error from Amethyst (https://nostr.build/p/nb6065.jpg). At the same time, the usual sending from the wallet to the same address works. It is only the NIP-57 mechanism that does not work. At the same time, invoices are created with an amount of 0 (https://nostr.build/p/nb6072.png , https://nostr.build/p/nb6070.png, https://nostr.build/p/nb6071.png), if I pay them manually from the admin panel, there are no problems - I can settle theirs.

**Comment by Kukks** [comment]
> In the beginning, everything worked. But I don't know what happened. But now, when the Lightning Address from BTCPay is registered in my profile and when I send zap to myself from the application or from the snort.social website, I see an error ("Could not fetch invoice from https://.../BTC/UILNURL/pay/i/INVOICE_ID"). Here, for example, is an error from Amethyst ([nostr.build/p/nb6065.jpg](https://nostr.build/p/nb6065.jpg)). At the same time, the usual sending from the wallet to the same address works. It is only the NIP-57 mechanism that does not work. At the same time, invoices are created with an amount of 0 ([nostr.build/p/nb6072.png](https://nostr.build/p/nb6072.png) , [nostr.build/p/nb6070.png](https://nostr.build/p/nb6070.png), [nostr.build/p/nb6071.png](https://nostr.build/p/nb6071.png)), if I pay them manually from the admin panel, there are no problems - I can settle theirs.

Invoices are meant to be generated as topup (0 amount invoices that will accept the first payment's value as the invoice's amount).

Some LN nodes do not allow paying yourself, such as CLN.
