### ISSUE TITLE
File Seller changes filename extension.

### ISSUE THREAD

**Issue by inpharmaticist** [Kukks/BTCPayServerPlugins#17]
I uploaded a jpeg and when testing the download link it changes to txt. It still works, but I have to change the name after downloading.

BTCPay Server v1.10.3
File Seller v1.0.0

**Comment by Kukks** [comment]
> I uploaded a jpeg and when testing the download link it changes to txt. It still works, but I have to change the name after downloading.
> 
> BTCPay Server v1.10.3 File Seller v1.0.0

Wow, people found this plugin fast :) 
Seems like a BTCPay issue not the plugin, will fix for next release!

**Comment by inpharmaticist** [comment]
Haha, I just happened to look at the available plugins the other day.
