### ISSUE TITLE
Plugins "Cannot install until dependencies are met"

### ISSUE THREAD

**Issue by ryenski** [Kukks/BTCPayServerPlugins#26]
Several [plugins](https://github.com/Kukks/BTCPayServerPlugins/blob/d24f2b54f6f0cab3be6cb052cc49f45a02b55ff4/Plugins/BTCPayServer.Plugins.BitcoinWhitepaper/BitcoinWhitepaperPlugin.cs#L10) are reporting that they require BTCPayServer: >=1.12.0, but the latest version is [1.11.7](https://github.com/btcpayserver/btcpayserver/releases/tag/v1.11.7). 

These plugins are unable to be installed due to the dependencies not being met.

**Comment by Kukks** [comment]
Yes, I wa trigger happy on the plugin builder and it doesn't have undo
functionality yet, just opened a pr to do that so I can revert soon

**Comment by ryenski** [comment]
Ah... no problem. I had just provisioned a new server and thought maybe I was missing some config.
