### ISSUE TITLE
Issue with nostr and wasabi plugin.

### ISSUE THREAD

**Issue by sinkthepink** [Kukks/BTCPayServerPlugins#42]
Hi, Everything was working fine BTCpay and wasabi plugin couple of days ago. One thing noticed out of the blue when checking Tor site was site home page would show (with PoS), but when trying to click through to form leading to timed invoice 502 errors began. Clearnet was fine. 

Then, tried to do some screwing around with local coordinator, activating and publishing to your nostr. There were some strange system actions and red warnings a few times, but system finally gave me an active, idle local coordinator. 

502 errors took down clearnet site too.

Deleted wasabi plugin. Back. Reinstalled. Same. Repeat... App follow through pages on Tor have never returned (after working previously).

**Comment by nostitos** [comment]
Problem was fixed in an update
