### ISSUE TITLE
Large gaps when CJ has issues, 

### ISSUE THREAD

**Issue by nostitos** [Kukks/BTCPayServerPlugins#44]
m/0/6348 to 6557 , 209 empty address.

Not 100% of what issue might have happened,

I've seen in logs webpage saying wasabi is blocked in the USA.

**Comment by Kukks** [comment]
> m/0/6348 to 6557 , 209 empty address.
> 
> Not 100% of what issue might have happened,
> 
> I've seen in logs webpage saying wasabi is blocked in the USA.

When coinjoins fail, the addresses generated specifically for it get reserved regardless. They were exposed to a coordinator and its users and therefore should be discarded. If reused in any future activity, the coordinator can correlate coins.
