### ISSUE TITLE
[Coinjoin] Trailing slash is required in coordinator info to connect

### ISSUE THREAD

**Issue by yahiheb** [Kukks/BTCPayServerPlugins#46]
I hope this time this is the right place for this issue. https://github.com/btcpayserver/btcpayserver/issues/6039#issuecomment-2154587528

This was first reported in Wasabi https://github.com/WalletWasabi/WalletWasabi/issues/13122 but apparently it is a problem on btcpayserver: https://github.com/WalletWasabi/WalletWasabi/pull/13146#discussion_r1627421410

When you set your coordinator in Wasabi to `https://btcpay.kruw.io/plugins/wabisabi-coordinator/` it works, but if you exclude the slash at the end `https://btcpay.kruw.io/plugins/wabisabi-coordinator` it does not work.

**Comment by Kukks** [comment]
> I hope this time this is the right place for this issue. [btcpayserver/btcpayserver#6039 (comment)](https://github.com/btcpayserver/btcpayserver/issues/6039#issuecomment-2154587528)
> 
> This was first reported in Wasabi [WalletWasabi/WalletWasabi#13122](https://github.com/WalletWasabi/WalletWasabi/issues/13122) but apparently it is a problem on btcpayserver: [WalletWasabi/WalletWasabi#13146 (comment)](https://github.com/WalletWasabi/WalletWasabi/pull/13146#discussion_r1627421410)
> 
> When you set your coordinator in Wasabi to `https://btcpay.kruw.io/plugins/wabisabi-coordinator/` it works, but if you exclude the slash at the end `https://btcpay.kruw.io/plugins/wabisabi-coordinator` it does not work.

This is correct,  it is an issue with the UriBuilder in .NET, or rather expected behavior.
