### ISSUE TITLE
[Nostr] NWC doesn't work with Mutiny Wallet

### ISSUE THREAD

**Issue by petzsch** [Kukks/BTCPayServerPlugins#54]
I've created a wallet connection in Mutiny and pasted the string back to btcpay and got this:

Invalid URL (No commands available or not all required commands are available (get_info, make_invoice, lookup_invoice, list_transactions))

Any chance to get this working? Would be kind of awesome.

**Comment by jooray** [comment]
As Mutiny is no longer being maintained, I recommend closing this.
https://blog.mutinywallet.com/mutiny-wallet-is-shutting-down/

**Comment by petzsch** [comment]
agreed. closed.
